FROM python:3.6-buster

RUN apt update
RUN apt install -y \
    libfuse2 \
    libfuse-dev \
    fuse 

COPY . /gfsfuse
RUN pip3 install -r /gfsfuse/requirements.txt

RUN addgroup --system --gid 1001 gfs
RUN useradd --uid 1001 --gid 1001 gfs -p gfsgfs

# ENV GFSAPI_HOST=10.88.88.183
# ENV GFSAPI_USER=
# ENV GFSAPI_PASSWORD=
ENV GFSAPI_HOST=gfs-api
ENV GFSAPI_PORT=5000

ENTRYPOINT ["/gfsfuse/bootstrap.sh"]