FROM python:3.6.12-alpine3.11

RUN apk update && \
    apk add \
        py3-pip \
        py3-gobject3 \
        libblockdev-dev \
        py3-libblockdev \
        py3-rtslib \
        build-base \
        udev 

COPY . /gfsfuse
RUN pip3 install -r /gfsfuse/requirements.txt

# ENV GFSAPI_HOST=10.88.88.183
# ENV GFSAPI_USER=
# ENV GFSAPI_PASSWORD=
ENV GFSAPI_HOST=gfs-api
ENV GFSAPI_PORT=5000

ENTRYPOINT ["/gfsfuse/bootstrap.sh"]